[project]
name = "fine-tuning"
version = "0.1.0"
description = "Fine-tune local models using Unsloth"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "unsloth",
    "torch",
    "datasets",
    "transformers",
    "ipykernel",
    "jupyter",
    "matplotlib>=3.11.1",
    "dotenv>=0.9.9",
    "seaborn>=0.13.2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
