experiment:
  name: "eb-qwen3.5-XXb-lora-522"
  seed: 8

model:
  name: "unsloth/Qwen3.5-27B"
  max_seq_length: 2048
  load_in_4bit: false
  full_finetuning: false
  dtype: "bfloat16"
  device_map: "auto"

data:
  train_path: "../data/echobot_old/train.jsonl"
  val_path: "../data/echobot_old/val.jsonl"

lora:
  r: 10
  lora_alpha: 20

  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj

  finetune_vision_layers: false
  finetune_language_layers: true
  finetune_attention_modules: true
  finetune_mlp_modules: true

  lora_dropout: 0.10
  bias: "none"
  use_gradient_checkpointing: "unsloth"

training:
  completion_only_loss: true
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 4

  eval_strategy: "steps"

  warmup_steps: 10
  num_train_epochs: 2
  optim: "adamw_8bit"

  logging_steps: 1
  dataset_num_proc: 1